### ISSUE TITLE
[Linux/1.5.2] Named back to gns3-converter but gns3 still expects gns3-net-converter

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-converter#4]
1.5.2 compiled from git sources
```
#gns3
Traceback (most recent call last):
  File "/usr/local/bin/gns3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gns3-net-converter>=1.3.0' distribution was not found and is required by gns3-gui
```

**Comment by jean-christophe-manciot** [comment]
I'm a bit lost with the naming conventions used here:
- the repository is named gns3-converter
- the build contains 
  - /usr/local/bin/gns3-converter
  - /usr/local/lib/python3.5/dist-packages/gns3_converter-1.3.0-py3.5.egg
  - /usr/share/doc/gns3-**net**-converter/
- gns3 expects gns3-**net**-converter
  So, which one is it?

**Comment by julien-duponchelle** [comment]
The install is done via:
pip install gns3-net-converter

But will create /usr/local/bin/gns3-converter

The problem is on pip gns3-converter is owned by Daniel Lintott
https://pypi.python.org/pypi/gns3-converter/1.2.4

But due to the fact we have no news from him. We have publish our fork under the name gns3-net-converter
https://pypi.python.org/pypi/gns3-net-converter/1.3.0

But for compatibility reason we use the same binary name, and package name on disk.

**Comment by jean-christophe-manciot** [comment]
Since gns3-converter is owned by Daniel Lintott and he doesn't want to or can't answer your request(s), you could draw the conclusions and :
- rename your forked repo gns3-net-converter
- rename the package gns3-net-converter
- create a pypi project gns3-net-converter
- include a symlink gns3-converter inside to point to gns3-net-converter for compatibility with earlier versions; It's easy to do with "/usr/local/bin/gns3-converter" and all "/usr/share/doc/gns3-converter" which should point to "/usr/local/bin/gns3-net-converter" and "/usr/share/doc/gns3-net-converter" respectively. I'm not a python expert, but this should also be doable for the python function itself so that if an older release of gns3(-gui) calls gns3-converter.
  @grossmj

**Comment by julien-duponchelle** [comment]
I will have a very conservative position here. But my position is what will not annoy users. Actually it's work even if not the cleaner solution.

> - rename your forked repo gns3-net-converter

I will say no, because If we do that we break link to this repo and people with git checkout. Also this will break detection of new version use by some packager.

> - rename the package gns3-net-converter

I will say no because this mean it will no longer work if you have a recent GNS3 and an older gns3 converter. 

Most packager don't care about the converter and will not check if they need to release a new gns3 converter version with the new GNS3 version.

Same for people installing it manually outside pip.

> - create a pypi project gns3-net-converter

It's the case
https://pypi.python.org/pypi/gns3-net-converter/

It's was require in order to be able to install it via pip.

> - include a symlink gns3-converter inside to point to gns3-net-converter for compatibility with earlier versions; It's easy to do with "/usr/local/bin/gns3-converter" and all "/usr/share/doc/gns3-converter" which should point to "/usr/local/bin/gns3-net-converter" and "/usr/share/doc/gns3-net-converter" respectively. I'm not a python expert, but this should also be doable for the python function itself so that if an older release of gns3(-gui) calls gns3-converter

It's not a good pratice because this could break tools that build package from the Python package. 

Perhaps @grossmj will have a different opinion. But I think he will have the same opinion.

Each time we have touched something on the distribution on this, something has broke on someone computer or even worse when it's impact a package thousand of computers.

If it was purely internally no problem for changing it, but I see too much possible impact and probably miss some.

The fork was require to provide a 1.3.13 with latest bug fixes and in case of the original repo disappear. But we don't plan more effort on this module. Transition from 1.X to 2.0 is a part of our code base with complete test suite to prevent regression, no longer a separate module maintain outside (also the transition is more details than big move).
